name: Build, Lint & Test CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build --stacktrace

  lint:
    name: Lint
    runs-on: [macos-latest]
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Android Lint
        run: ./gradlew lint

  test:
    name: Run Unit Tests
    runs-on: [macos-latest]
    needs: [build, lint]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Tests
        run: ./gradlew test --stacktrace
